# Generated by Django 3.0 on 2020-11-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_csv_activated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv',
            name='activated',
        ),
    ]
